swiftmailer:
    spool: { type: 'memory' }
    transport:        gmail
    username:         maurochojrin@gmail.com
    password:         escuelait
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false